version: "3"
services:


  app:
    image: codernoone/webflux_rest_api:v2
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

    ports:
      - "8080:8080"
    networks:
      - net

  mongo1:
    hostname: mongo_db
    image: mongo:4.4.4
    ports:
      - "27018:27017"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    networks:
      - net


  mongo2:
    hostname: mongo_db
    image: mongo:4.4.4

    ports:
      - "27016:27017"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    networks:
      - net

  mongo_db:
    hostname: mongo_db
    image: codernoone/mongo_rs_initiated
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - net

networks:
  net:
    driver: overlay