version: '3.3'

services:

  mongo_db:
    image: mongo:latest
    container_name: 'mongo_db'
    ports:
      - "1000:27017"
    entrypoint:  [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    restart: always

  cinema-webflux-rest-api:
    image: cinema-webflux-rest-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo_db
    ports:
      - "8080:8080"