version: '3.4'

services:

  mongo_db:
    image: codernoone/mongo_with_rs0
    container_name: mongo_db
    ports:
    - "27017:27017"
    restart: always
    volumes:
      - ./mongo/volume:/data/db
    networks:
      - net

  cinema-webflux-rest-api:
    image: codernoone/webflux-rest-api
    container_name: app
    depends_on:
      - mongo_db
    ports:
      - "8080:8080"
    restart: always
    networks:
      - net

networks:
  net:

