server:
  port: 8080

spring:
  data:
    mongodb:
      database: cinema_db
      host: mongo_db
      replica-set-name: rs0
      port: 30001

jwt:
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

jasypt:
  encryptor:
    password: password

springdoc:
  api-docs:
    groups:
      enabled: true
  packages-to-scan: com.app
  swagger-ui:
    path: /docs

change-logs-scan-package: com.app.infrastructure.mongo.initscripts
adminusername: admin123