server:
  port: 9010

spring:
  data:
    mongodb:
      database: db2
      host: localhost
      port: 27017
      replica-set-name: rs0

  mail:
    host: smtp.gmail.com
    username: firelight.code@gmail.com
    password: rxzbacwpboqvjllq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

change-logs-scan-package: com.app.infrastructure.mongo.initscripts
adminusername: admin123

jasypt:
  encryptor:
    password: password