server:
  port: 9001

spring:
  data:
    mongodb:
      database: cinema_db
      host: localhost
      port: 27017
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200

  elasticsearch:
    rest:
      uris:http://localhost:9200

jwt:
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

