server:
  port: 9010

spring:
  data:
    mongodb:
      database: cinema_db2
      host: localhost
      port: 27017

jwt:
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

