server:
  port: 9010

spring:
  data:
    mongodb:
      database: db2
      host: localhost
      port: 27017
      replica-set-name: rs0
jwt:
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

change-logs-scan-package: com.app.infrastructure.mongo.initscripts

adminusername: admin1111

jasypt:
  encryptor:
    password: password