server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://mongo1:30001,mongo2:30002,mongo3:30003/?replicaSet=rs0
      database: cinema_db

jwt:
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

jasypt:
  encryptor:
    password: password

springdoc:
  api-docs:
    groups:
      enabled: true
  packages-to-scan: com.app
  swagger-ui:
    path: /docs

change-logs-scan-package: com.app.infrastructure.mongo.initscripts
adminusername: admin123
